apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-43ge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-43ge
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-43ge
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-43ge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-43ge
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iqhy-tenant/rhtap-demo-app/hacbs-test-project-43ge@sha256:5bd561fab7a8be95db38476b847ff207286e3987b206384abf835a8ca9d629db
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
